image:
  file: .gitpod.Dockerfile

ports:
  - port: 3004
    onOpen: open-browser

tasks:
  - init: |
      yarn global add markdownlint-cli
      yarn install
      bundle install -j $(nproc)
    command: bundle exec nanoc live --port=3004
