image:
  file: .gitpod.Dockerfile

ports:
  - port: 3004
    onOpen: open-browser

tasks:
  - init: |
      bundle install
      yarn install --frozen-lockfile
      bundle exec rake
      bundle exec nanoc compile
    command: bundle exec nanoc live --port=3004
