inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

CodeReuse/ActiveRecord:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
