#
# Copy this Dockerfile to the root of each branch you want to create an archive
#

# Set to the version for this archive (must match the branch name)
ARG VER=14.2

# Replace the versions to march the stable branches of the upstream projects
ARG BRANCH_EE=14-2-stable-ee
ARG BRANCH_OMNIBUS=14-2-stable
ARG BRANCH_RUNNER=14-2-stable
ARG BRANCH_CHARTS=5-2-stable

# This image comes from the Dockerfile.builder.onbuild file
# https://gitlab.com/gitlab-org/gitlab-docs/blob/main/dockerfiles/Dockerfile.builder.onbuild
# Build the website
FROM registry.gitlab.com/gitlab-org/gitlab-docs:builder-onbuild AS builder

# This image comes from the Dockerfile.nginx.onbuild file
# https://gitlab.com/gitlab-org/gitlab-docs/blob/main/dockerfiles/Dockerfile.nginx.onbuild
# Copy the generated HTML files to a smaller image
FROM registry.gitlab.com/gitlab-org/gitlab-docs:nginx-onbuild
