#
# Copy this Dockerfile to the root of each branch you want to create an archive
#

# Set to the version for this archive (must match the branch name)
ARG VER=11.5

# Replace the versions to march the stable branches of the upstream projects
ARG BRANCH_EE=11-5-stable-ee
ARG BRANCH_CE=11-5-stable
ARG BRANCH_OMNIBUS=11-5-stable
ARG BRANCH_RUNNER=11-5-stable

# This image comes from the Dockerfile.builder.onbuild file
# https://gitlab.com/gitlab-org/gitlab-docs/blob/master/dockerfiles/Dockerfile.builder.onbuild
# Build the website
FROM registry.gitlab.com/gitlab-org/gitlab-docs:builder-onbuild AS builder

# This image comes from the Dockerfile.nginx.onbuild file
# https://gitlab.com/gitlab-org/gitlab-docs/blob/master/dockerfiles/Dockerfile.nginx.onbuild
# Copy the generated HTML files to a smaller image
FROM registry.gitlab.com/gitlab-org/gitlab-docs:nginx-onbuild
